// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

import Hero from "./assets/images/HEROV2.png";
import OurOfferings1 from "./assets/images/hero-2-v2.png";
import OurOfferings2 from "./assets/images/students-brainstorming.png";
import WhyChooseUs from "./assets/images/man_standing_in_coat.png";
import LogoMark from "./assets/images/logo-mark.svg";
import HeroCapabilityConsulting from "./assets/images/students-brainstorming.png";
import HeroLearningExperiencePlatform from "./assets/images/consulting-hero-v2.jpg";
import Step1Card1 from "./assets/images/step1-card1.jpg";
import Step1Card2 from "./assets/images/step1-card2.svg";
import Step1Card3 from "./assets/images/step1-card3.svg";
import Step2Img from "./assets/images/step2-img.jpg";
import Step3Card1 from "./assets/images/Step3-Card1.svg";
import Step3Card2 from "./assets/images/step3-card2.svg";
import Step3Card3 from "./assets/images/step3-card3.jpg";
import LearningImage1 from "./assets/images/learning-img1-v2.jpg";
import LearningImage2 from "./assets/images/learning-img2-v2.jpg";
import LearningImage3 from "./assets/images/learning-img-3-v2.jpg";
import Collaboration from "./assets/images/colloboration-v2.png";
import HeroAbout from "./assets/images/hero_about-v2.png";
import Realisation from "./assets/images/realisation-v2.png";
import OurAim from "./assets/images/our-aim-v2.jpg";

import Logo from "./assets/logo.svg";
import DownArrow from "./assets/downarrow.svg";
import GreenUpArrow from "./assets/green-up-arrow.svg";
import Automation from "./assets/automation.svg";
import AdsClick from "./assets/ads-click.svg";
import ChatBubble from "./assets/chat-bubble.svg";
import Linkedin from "./assets/linkedin.svg";
import Twitter from "./assets/twitter.svg";
import GraduationCap from "./assets/graduation-cap.svg";
import Learning from "./assets/learning.svg";
import Game from "./assets/game.svg";
import JobSearch from "./assets/job-search.svg";
import UserRoles from "./assets/user-roles.svg";
import Rocket from "./assets/rocket.svg";
import Infra from "./assets/infra.svg";
import Board from "./assets/board.svg";
import Forum from "./assets/forum.svg";
import Star from "./assets/star.svg";
import AdsClick2 from "./assets/ads_click2.svg";
import SearchInsights from "./assets/search_insights.svg";
import Tactic from "./assets/tactic.svg";
import Menu from "./assets/menu.svg";
import Close from "./assets/close.svg";
import Mail from "./assets/mail.svg";
import Call from "./assets/call.svg";
import Check from "./assets/check.svg";
import Map from "./assets/map.svg";
import ChevronRight from "./assets/chevron_right.svg";

export const SITE_TITLE = "Astro Blog";
export const SITE_DESCRIPTION = "Welcome to my website!";

export const LOGO = Logo;
export const HERO = Hero;
export const LOGOMARK = LogoMark;
export const HERO_CAPABILITY_CONSULTING = HeroCapabilityConsulting;
export const HERO_LEARNING_EXPERIENCE_PLATFORM = HeroLearningExperiencePlatform;
export const STEP1_CARD1 = Step1Card1;
export const STEP1_CARD2 = Step1Card2;
export const STEP1_CARD3 = Step1Card3;
export const STEP2_IMG = Step2Img;
export const STEP3_CARD1 = Step3Card1;
export const STEP3_CARD2 = Step3Card2;
export const STEP3_CARD3 = Step3Card3;
export const LEARNING_IMAGE1 = LearningImage1;
export const LEARNING_IMAGE2 = LearningImage2;
export const LEARNING_IMAGE3 = LearningImage3;
export const COLLABORATION = Collaboration;
export const HERO_ABOUT = HeroAbout;
export const REALISATION = Realisation;
export const OUR_AIM = OurAim;

export const DOWNARROW = DownArrow;
export const GREENUPARROW = GreenUpArrow;
export const OUROFFERINGS1 = OurOfferings1;
export const OUROFFERINGS2 = OurOfferings2;
export const WHYCHOOSEUS = WhyChooseUs;
export const AUTOMATION = Automation;
export const ADSCLICK = AdsClick;
export const CHATBUBBLE = ChatBubble;
export const LINKEDIN = Linkedin;
export const TWITTER = Twitter;
export const GRADUATIONCAP = GraduationCap;
export const LEARNING = Learning;
export const GAME = Game;
export const JOBSEARCH = JobSearch;
export const USERROLES = UserRoles;
export const ROCKET = Rocket;
export const INFRA = Infra;
export const BOARD = Board;
export const FORUM = Forum;
export const STAR = Star;
export const ADSCLICK2 = AdsClick2;
export const SEARCHINSIGHTS = SearchInsights;
export const TACTIC = Tactic;
export const MENU = Menu;
export const CLOSE = Close;
export const MAIL = Mail;
export const CALL = Call;
export const CHECK = Check;
export const MAP = Map;
export const CHEVRONRIGHT = ChevronRight;
